[package]
name = "prism_rust_implementation_example"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10.4"
qrcode = "0.12.0"
